[project]
name = "crud-api-postgres"
version = "0.1.0"
description = ""
authors = [
    {name = "Matheus Ramos",email = "matheussoaresramos@gmail.com"}
]
readme = "README.md"
requires-python = "3.12.1"
dependencies = [
    "fastapi (>=0.121.3,<0.122.0)",
    "fastapi[standard] (>=0.121.3,<0.122.0)",
    "streamlit (>=1.51.0,<2.0.0)",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "pydantic (>=2.12.4,<3.0.0)",
    "pydantic[email] (>=2.12.4,<3.0.0)",
    "plotly (>=6.5.0,<7.0.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
